
#This script contains the functions that generate the simmulated dataset

#Generate Medd 

# This function randomly flips the value of a variable to 0 by multiplying the original value with either 1 or 0.
# The probability of this number multiplying 0 is 0.995, and multiplying 1 is 0.005.
add_random_zero <- function(var1){
  
  # This inner function takes a value and randomly multiplies it with 0 or 1.
  add_zero <- function(x) {
    
    # Randomly choose between 0 and 1, with probabilities of 0.995 and 0.005 respectively.
    add <- sample(c(0, 1), size = 1, replace = TRUE, prob = c(0.995, 0.005))
    
    # Multiply the value with the randomly chosen number (either 0 or 1).
    new_va <- x * add
    return (new_va)
  }
  
  new_variable <- unlist(lapply(var1, add_zero))
  print(summary(new_variable))
  return (new_variable)
  
}



#Generate Medd for month 1  to month 11, Each month is generated by adding a value to the preceding month
# The function `add_Medd` takes three arguments: `var1` (a vector representing the variable to which a value will be added), `probs` (a vector representing the probabilities of the random values being 0 or a random value within the range of -5000 to `max_rand`), and `max_rand` (a parameter representing the upper limit of the random values that can be added to `var1`). 

# Within the function, there is a nested function `add_val` that takes a single value `x` and adds a random value to it. The random value is generated using the `runif` function, which draws a uniform random value within the range of -5000 to `max_rand`. 

# The possible values that can be added to `x` are defined in the vector `c(0, random_add)`, with the probabilities for each value defined in the `probs` vector. If the randomly selected value is 0, the final value will be `x` (i.e., no change). Otherwise, the final value will be `x` plus the randomly selected value.



add_Medd <- function(var1, probs, max_rand){
  # Function to add a value to a an observation x, the prob of this value to be 0 or a random value is specified in probs
  add_val <- function(x) {

    # Generate a random number (random_add) within the range between -5000 and max_rand 
    random_add <- runif(1, min=-5000, max=max_rand)
    # We'll add the number 'ad' to the the observation value and the probability of "ad" to be 0 or random_add is defined in the "prob" vector
    ad <- sample(c(0, random_add), size = 1, replace = TRUE, prob = probs)
    new_va <- x + ad

    # If the new value is negative, set it to 0
    if (new_va < 0){
      return (0)
    }
    return (new_va)

  }

  # Apply the add_val function to each element in the variable
  new_variable <- unlist(lapply(var1, add_val))
  print(summary(new_variable))
  print(cor.test(var1, new_variable))


  return (new_variable)


}

# The function add_random_zero_hospital takes in a variable var1 and converts some of its observations to 0
add_random_zero_hospital <- function(var1){
  
  #  Inner function add_zero takes in a value x and converts it to either 0 or 1 with a 99% probability of being 0 and 1% probability of being 1
  add_zero <- function(x) {
    # Sample a value from 0 or 1, the probability of this value to be 0 is 0.99., 1 is 0.01
    add <- sample(c(0, 1), size = 1, replace = TRUE, prob = c(0.99, 0.01))
    # New value is the multiplication of original value and the sampled value
    new_va <- x * add
    return (new_va)
  }
  
  # Apply the add_zero function to each observation in var1 using lapply and unlist the result
  new_variable <- unlist(lapply(var1, add_zero))
  print(summary(new_variable))
  return (new_variable)
  
}


#reduce_count, reduce_counts_appointment, add_counts are functions to create the hospital visit variables. Details of these three functions are describe in this paragrah on the draft:

#"let $Z$ denotes a 30-day or 730-day variable, $Z'$ denotes a 30-day variable or 730-day variable, if $Z$ is a 30-day variable and $Z'$ is a 730-day variable , $Z' = Z + \delta$, conversely, if  $Z$  is a 730-day variable $Z'$ is a 30-day variable, $Z' = Z - \delta$. $\delta$ is the number of hospital visit count assigned according to a predefined probability $P$, $Range(\delta)$ = \{0, 1, ..., $q$ \}, $q$ is an upper bound of $\delta$ and it is equal to the maximum number of visits to the corresponding healthcare provider. 

# Depending on the structural of the new variable, we designed two functions to generate Z'. In function add_counts, we defined  $P(\delta = 0) = p_1$, $P (\delta \ \in (1, \tau) ) = p_2$ and $P (\delta \ \in (\tau, q) ) = p_3$, $\tau$ denotes a threshold, $\tau < q$ and $p_2 > p_3$". In function reduce_count, reduce_counts_appointment, we defined $P(\delta = 0) = p_1$, $P (\delta != 0) = p_2$. In addition, we randomly flip some of the values greater than a threshold to a smaller value to simulate the longtail effect of the variable.


#Reduce counts from the 730 days variable to create the 30 days variable Draft, see section 4.2 paragraph 2-3
# This function is similar to the reduce_count function, except that we set the probability of the deducted value to be a non zero as much smaller than the proabality of this value being 0

reduce_counts_appointment <- function(var1, q, threshold){
  
  # The function first defines an inner function called "add_val", which adds a value (delta) to a given number. 𝛿 is  assigned according to a predefined probability 𝑃(probs). Range (delta) = {0, 1, ..., 𝑞 }, 𝑞 is an upper bound of 𝛿and it is equal to the maximum number of visits to the corresponding healthcare provider.
  
  add_val <- function(x) {
    
    # Define a probability vector with q (maximum number of visit) elements,  the first value (0) has a probability of 0.2, while the rest of the values have a probability of 1/q.
    probs = c(.2, rep(1/q, q)) 
    
    # Sample a value from 0 to q (maximum number of visit) to be subtracted from the given number. 
    add <- sample(x = 0:q, prob = probs, size = 1, replace = TRUE) 
    
    # Calculate the new value by subtracting the sampled value.
    new_va <- x - add
    
    # If the new value is below the threshold and non-negative, it is returned as is.
    if (new_va < threshold & new_va >= 0){
      return (new_va)
    }
    
    # If the new value is above or equal to the threshold, it is converted to a random number between 0 and the threshold. (To simulate the longtail effect)
    if (new_va >= threshold){ 
      return (round(runif(1, min=0, max=threshold), digits = 0))
    }
    
    else{
      return (0)
    }
  }
  
  #Apply the above procedures to every value in the vector
  new_variable <- unlist(lapply(var1, add_val))
  #checking the statistics
  print(summary(new_variable))
  print(sd(new_variable))
  
  return (new_variable)
  
  
}

# This function adds counts to the 30-days ("var1") variable, which represents a 30-day variable. Draft, see section 4.2 paragraph 2-3
# The "q" parameter represents the maximum value that the new variable can have.
# The "threshold" parameter represents the value above which the probability of being assigned a zero value is 0.0000001, otherwise it is 0.005.

add_counts <- function(var1, q, threshold){
  
  
  # The function defines an inner function called "add_val", which adds a value (delta) to a given number.
  add_val <- function(x) {
    
    # The probability of assigning different values to "delta" is defined based on the probabilities specified in the "probs".
    
    #The probability of "delta" being zero is 0.9, so that most observations have 0 hospital visits. The remaining 10% of observations have non-zero values for "delta", with different probabilities based on "threshold". If the value is above "threshold", the probability of being assigned a zero value is 0.0000001. Otherwise, the probability of being assigned a
    
    probs = c(.9, rep(.005, threshold), rep(.0000001, q-threshold))
    
    # "delta" is chosen randomly from the range {0, 1, ..., q} based on the probabilities specified in "probs".
    delta <- sample(x = 0:q, prob = probs, size  = 1, replace = TRUE) 
    # The original number is then added to "delta" to create a new value for the variable.
    new_va <- x + delta
    return (new_va)
  }
  # This generates a new variable called "new_variable".
  new_variable <- unlist(lapply(var1, add_val))
  
  #View the statistics
  print(cor(new_variable, var1))
  print(summary(new_variable))
  print(sd(new_variable))
  
  return (new_variable)
  
  
}




# Function to generate a Pareto distribution Draft, see section 4.2 paragraph 2
#   Parameters:
#     location: vector of positive location parameters
#     shape: vector of shape parameters
#     num: number of elements in the variable

get_pareto_var <- function(location, shape, num){
  
  # Generate random deviates from Pareto distribution
  data <- rpareto(num, location, shape)
  
  #Round up the values
  data <- round(data, digits = 0)
  
  # Add some noise to the data
  # The noise should be very small and should not significantly affect the distribution, here we set the noise can be 0, 1, 3, 6, 8,  the probabilities of each noise value occurring are specified by the prob vector
  noise <- sample(x = c(0, 1, 3, 6, 8),  size  = num_of_obs, replace = TRUE, prob = c(0.995, 0.0001, 0.0001, 0.0001, 0.0001))
  new_data <- data + noise
  return (new_data)
  
}




# This function randomly converts some of the values of a variable to a smaller number by multiplying the original value with either 0 or 1, then convert the 0 to a smaller number. 
# The probability of this number multiplying 0 is 0.6, and multiplying 1 is 0.4.
add_random_zero_appointment <- function(var1){
  # This inner function takes a value and randomly multiplies it with 0 or 1.
  add_zero <- function(x) {
    
    # Randomly choose between 0 and 1, with probabilities of 0.6 and 0.4 respectively.
    add <- sample(c(0, 1), size = 1, replace = TRUE, prob = c(0.6, 0.4))
    # Multiply the value with the randomly chosen number (either 0 or 1).
    new_va <- x * add 
    
    # If the new value is 0, replace it with a random number between 0 and 40.
    if (new_va == 0) { 
      new_va <- round(runif(1, 0, 40), digit = 0)
    }
    else{
      return (new_va)
    }
    return (new_va)
  }
  
  new_variable <- unlist(lapply(var1, add_zero))
  print(summary(new_variable))
  return (new_variable)
  
}





